### ISSUE TITLE
private-network-ibft-automated breaks outside of default namespace

### ISSUE THREAD

**Issue by jonaskint** [PegaSysEng/besu-kubernetes#15]
I've been testing out the automated ibft besu helmfile setup and noticed that the genesis job did not have the right permissions outside of the default namespace.

https://github.com/PegaSysEng/besu-kubernetes/blob/master/helmfile/private-network-ibft-automated/besu-genesis/templates/role-binding.yaml#L50

I've created a small PR: https://github.com/PegaSysEng/besu-kubernetes/pull/14

**Comment by joshuafernandes** [comment]
Merged, thanks for that @jonaskint
