### ISSUE TITLE
Validators cannot find each other

### ISSUE THREAD

**Issue by ppoliani** [PegaSysEng/besu-kubernetes#20]
I used the k8s manifest fast to deploy the a private-ibft network. I followed the instructions as stated in the readme file. Everything looks to be deployed to my k8s cluster, however looking into the logs of each validator I can see that there is a issue with finding peer nodes. More specifically, I can see the following error:

```
2020-01-11 08:57:02.338+00:00 | EthScheduler-Timer-0 | INFO | FullSyncTargetManager | No sync target, wait for peers.
```

I then tried to execute a json rpc in one of the validators pod.

```
curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' $BESU_VALIDATOR1_SERVICE_HOST:8545
```

The result I get back is:

```
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : "0x5"
}
```

It looks like validator1 which is the bootnode, does have 5 peers connected. However, the logs (as shown above) suggest that there is an issue in syncing with the peers.

**Comment by joshuafernandes** [comment]
Hello @ppoliani 

Thank you for this. Could you provide us with a little more info which one this was please i.e kubectl or helm? Also with both charts there is a prometheus & grafana deployment done with an ingress (in the monitoring namespace) to the grafana container. Could you confirm that you saw that and that you saw the chain height grow in that graph or if it was stuck at 0 please?

**Comment by ppoliani** [comment]
Hi @joshuafernandes 

Yes sure. I'm using kubectl folder and deploy the services individually. 

Here is the grafana dashboard which shows that the block height is 0.

<img width="1387" alt="Screenshot 2020-01-13 at 09 24 00" src="https://user-images.githubusercontent.com/1389619/72244618-93676b00-35e6-11ea-8b1a-4f7a348b9a4f.png">

I have done this quite a few times; always following the instructions in the Readme file but still all validators show the same message in the logs

`FullSyncTargetManager | No sync target, wait for peers.`.

Each of the validator pods start with the following command:

```
'exec /opt/besu/bin/besu \\--genesis-file=/configs/genesis.json \\--node-private-key-file=/secrets/key \\--rpc-http-enabled \\--rpc-http-host=0.0.0.0 \\--rpc-http-port=8545 \\--rpc-http-cors-origins=${NODES_HTTP_CORS_ORIGINS} \\--rpc-http-api=ETH,NET,IBFT \\--graphql-http-enabled \\--graphql-http-host=0.0.0.0 \\--graphql-http-port=8547 \\--graphql-http-cors-origins=${NODES_HTTP_CORS_ORIGINS} \\--rpc-ws-enabled \\--rpc-ws-host=0.0.0.0 \\--rpc-ws-port=8546 \\--metrics-enabled=true \\--metrics-host=0.0.0.0 \\--metrics-port=9545 \\--host-whitelist=${NODES_HOST_WHITELIST} \\--bootnodes=enode://${VALIDATOR1_PUBKEY}@${BESU_VALIDATOR1_SERVICE_HOST}:30303'
```

I also tried to check both `VALIDATOR1_PUBKEY` and `BESU_VALIDATOR1_SERVICE_HOST` env variables inside each of the validator pods and they all seem to have the correct value.

**Comment by joshuafernandes** [comment]
Hello @ppoliani 

Thank you for that information. This is quite interesting & I've not been able to reproduce that via the kubectl method either. I think this might be more environment specific, so we'll try and replicate what you have if possible and see how that goes.  Would you be able to give us some more information on your setup and where you are deploying this to please? Could you confirm that port 30303 on the validators & services is open to both UDP & TCP and whether you are using the same keys & genesis file here or if its been generated afresh please?

I'm spinning this locally on Minikube (1.6.2), Ubuntu 18.04 LTS and running at commit id 8bb1d078bfda3b8f0d432e1ab637e251d892df6f on the master branch of this repo. I've also tested this on EKS & AKS so I'm puzzled. I've gone through the steps in the Readme.md and deployed things in the same order as the deploy steps (line 40 onwards) https://github.com/PegaSysEng/besu-kubernetes/blob/master/kubectl/private-network-ibft/README.md#L40 

I've got 4 validators + 2 nodes up and all producing blocks fine. 
![pods](https://user-images.githubusercontent.com/3722503/72246561-b58cd780-363e-11ea-80bc-6aafe50a3dc7.png)
![dash](https://user-images.githubusercontent.com/3722503/72246576-bc1b4f00-363e-11ea-87b6-a65fe9350c48.png)

**Comment by ppoliani** [comment]
@joshuafernandes 

Thank you for your detailed explanation. I was running on the same commit as you mentioned. My cluster is deployed on DO.

I tried to clean everything and start from scratch and it worked perfectly fine. The only thing differently this time is I used the `hyperledger/besu:develop` image to create the keys., whereas before I would use `hyperledger/besu:latest`. Not sure if that made any difference. 

In any case, it worked this time. Apologies for any inconvenience and thanks for the help :)

**Comment by joshuafernandes** [comment]
> @joshuafernandes
> 
> Thank you for your detailed explanation. I was running on the same commit as you mentioned. My cluster is deployed on DO.
> 
> I tried to clean everything and start from scratch and it worked perfectly fine. The only thing differently this time is I used the `hyperledger/besu:develop` image to create the keys., whereas before I would use `hyperledger/besu:latest`. Not sure if that made any difference.
> 
> In any case, it worked this time. Apologies for any inconvenience and thanks for the help :)

Thanks for the update @ppoliani. no apologies needed, happy to help and glad to hear its working. I'll look into the images and see if we have anything different that would cause that.
