### ISSUE TITLE
Private Clique network

### ISSUE THREAD

**Issue by ppoliani** [PegaSysEng/besu-kubernetes#21]
It would be a good addition to be able to setup a Clique network. I'd be happy to look into it if I have some guidelines.

**Comment by joshuafernandes** [comment]
Hello @ppoliani 

Certainly :) Be more that happy for you to look into it !

The Clique setup should be identical to the IBFT setup with slight differences to the genesis file - details for the implementation are in our [quickstarts](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-Private-Clique-Network/) and the overview can be found [here](https://besu.hyperledger.org/en/stable/Concepts/Consensus-Protocols/Overview-Consensus/)

Give us a yell if you have any questions and we can work through it

Cheers

**Comment by ppoliani** [comment]
The only worry is that there is no equivalent command to `operator generate-blockchain-config` for the Clique network. I'm not sure how we can replicate the creation of private/public key pairs for each node.

**Comment by joshuafernandes** [comment]
Hi @ppoliani - agreed, the besu CLI doesnt automate the creation of the clique genesis file and its manual but largely similar to the IBFT.

So it should be ok to reuse the keys from the IBFT setup or create a set manually and then put them into the genesis file. Once you have the keys, you can add the addresses into the `extradata` field for the genesis file by concatenating them (eg2 here https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Clique/#extra-data)  and fire the network up 

Let me know if you run into any issues or if you have any more questions and we can work though them :)

**Comment by ppoliani** [comment]
Thanks @joshuafernandes. I will give it a go and will let you know about my progress.

**Comment by joshuafernandes** [comment]
Thank you @ppoliani :) Clique setup added in with #22
