### ISSUE TITLE
Helm install in namespace other than `besu` still installs in `besu` ns

### ISSUE THREAD

**Issue by marcelloromani** [PegaSysEng/besu-kubernetes#32]
How to reproduce
```
helm upgrade --install besu --namespace besudemo ./besu
```

Expected: release installed in namespace `besudemo`

Actual: namespace `besudemo` is empty, release installed in namespace `besu`.

**Comment by marcelloromani** [comment]
Workaround: specify the namespace in a `values.yaml` file or using `--set namespace=foo`

**Comment by joshuafernandes** [comment]
Hello @marcelloromani this is by design and is in the main README.md here https://github.com/PegaSysEng/besu-kubernetes
