### ISSUE TITLE
How to login to Grafana and how to get the besu node host link

### ISSUE THREAD

**Issue by yehia67** [PegaSysEng/besu-kubernetes#55]
Hello,
I am new at BESU and have some questions. I am following this readme [file](https://github.com/PegaSysEng/besu-kubernetes/tree/master/kubectl/ibft2). 

First, for Grafana it asks me for username and password where should I get them?

Second, to make curl calls I need the besu node host link where I could find it?

 curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' 172.17.0.2:8545

I tried to add the minikube IP or the localhost but it doesn't work
```
docker@minikube:~$ curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":1}' 127.0.0.1:8545
curl: (7) Failed to connect to 127.0.0.1 port 8545: Connection refused
```

**Comment by joshuafernandes** [comment]
Hello @yehia67 

Credentials for grafana are in that readme file - last bullet point under the section 'Flow of the process'

```Credentials for grafana are admin:password. When grafana loads up select the "besu Dashboard"```

To get the IP's of the pods you can use kubectl or the dashboard whichever is available to you:
eg: 

```kubectl get pod -n <NAMESPACE> -o wide
```

If you are using minikube then you need to run `minikube ssh` first to get onto the vm and then you will be able to run those curl requests. To be able to make curl reqs from your host, you need to deploy an ingress and then you can use the minikube ip directly

Hope that helps

Cheers

**Comment by yehia67** [comment]
Thank you  very much! @joshuafernandes
